from app.prompts.selection_reviewer import SELECTION_PROMPT, SELECTION_PROMPT_VERSION
from app.prompts.technical_evaluator import TECHNICAL_PROMPT, TECHNICAL_PROMPT_VERSION

__all__ = ["SELECTION_PROMPT", "SELECTION_PROMPT_VERSION", "TECHNICAL_PROMPT", "TECHNICAL_PROMPT_VERSION"]
